### ISSUE TITLE
Test the Blueprint itself

### ISSUE THREAD

**Issue by novusnota** [ton-org/blueprint#114]
Otherwise we have a very peculiar example of a testing framework, which doesn't spot no tests itself. They would help uncover much more bugs than trial-and-error approach.

**Comment by anton-trunov** [comment]
@novusnota Could you expand on what you mean here? A testing framework for a general purpose language that does not test itself sounds a bit like nonsense, indeed. However, Blueprint is a tool to help with testing DSL programs (smart contracts) and not general purpose programs.

**Comment by novusnota** [comment]
@anton-trunov for example, it could have e2e CI tests with Tact and FunC. It would creating new projects, change compiler versions, check that everything builds and tests.

Because as of now it's somewhat annoying to debug the Blueprint in a pipeline, especially when the target OS is unaccessible:

![shifu-meme-blueprint-2](https://github.com/ton-org/blueprint/assets/68142933/e3625ed0-8b33-426b-8147-8881f64ee842)

**Comment by anton-trunov** [comment]
@novusnota that's more or less issue #115

**Comment by novusnota** [comment]
Yup, but there are unit tests too, which can help make sure (or at least more confident than before), that the internals work fine

**Comment by anton-trunov** [comment]
Unit tests are double-edged things -- they can sufficiently slow down project development by unnecessarily fixing its internal structure. End-to-end tests are something that I personally would prefer.

**Comment by novusnota** [comment]
Agreed. Shall this be closed in favor of #115 then?

**Comment by anton-trunov** [comment]
I guess this one can be closed indeed. But please do could share some more concrete suggestion in #115
