### ISSUE TITLE
Exception when running "blueprint run" command in version 0.22

### ISSUE THREAD

**Issue by maqicheng123** [ton-org/blueprint#139]
I'm using version 0.22 and when run the command "blueprint run" get the following error:
TypeError: Cannot read properties of undefined (reading 'slice')
Roll back to 0.21 to use this command normally.
I looked at the problem in the package and found that there was a problem with the optimized findScripts function.

**Comment by HanYinBingReXue** [comment]
Saved my life!
Thank you !

**Comment by Brand151** [comment]
> Saved my life!
> Thank you !

**Comment by LidamaoHub** [comment]
nice! thank you!

**Comment by Shumnijkot** [comment]
Why close? 
They still haven't rolled new version out. And ppl will have problem when creating ton@latest

**Comment by nickshatilo** [comment]
the issue is related to node.js dirent.path property which was added in `18.17` version and in `20.1.0`, but later it was deprecated.

as a workaround just use node versions supporting this api and it will work.

https://nodejs.org/api/fs.html#direntpath
