### ISSUE TITLE
TypeError: paramSet.isSubsetOf is not a function

### ISSUE THREAD

**Issue by bytemtek** [ton-org/blueprint#157]
When I try create new project I get this error.
Is anybody have idea how can I fix it ?

![Screenshot 2024-11-19 at 17 06 25](https://github.com/user-attachments/assets/bbe1f865-4d46-46dd-9f49-9cdc4667774c)

**Comment by 0xdino** [comment]
Ensure that your Node.js version is 22.0.0 or higher

**Comment by bytemtek** [comment]
> Ensure that your Node.js version is 22.0.0 or higher

Thank you so much after upgrade NodeJS problem solved.

**Comment by anton-trunov** [comment]
Thank you for checking!
