### ISSUE TITLE
Issue with missing options while running 'yarn blueprint build'

### ISSUE THREAD

**Issue by howardpen9** [ton-org/blueprint#38]
Hi, why I can't see the other option when I try to run `build`.

For me, I had added the new wrappers in the folders. (as you can see, different files)

But I can't find the option when after I run the `yarn blueprint build`

![image](https://user-images.githubusercontent.com/36764495/230575640-b0cd5152-bd3c-4e80-a325-789ef4d7ff61.png)

![image](https://user-images.githubusercontent.com/36764495/230575611-89c824ab-46b6-4a39-94e6-406b7b8046d0.png)

**Comment by krigga** [comment]
`build` scans for .compile.ts files, which are created for you if you use `blueprint create`, but otherwise you need to create them yourself. Just copy any existing one and change the filename of the .compile.ts file itself and the name of the .fc file inside
