### ISSUE TITLE
[Feature] Implement non-interactive project creating.

### ISSUE THREAD

**Issue by braveltd** [ton-org/blueprint#40]
Right now we use `npx create ton@latest`, then define project folder and first created contract name and type of contract...

This is interactive, but we can make it non-interactive.

### **For example:**
**NextJS**:
`pnpm create next-app` - template for nextjs. [reference](https://nextjs.org/docs/pages/api-reference/create-next-app)
non-interactive way - `pnpm create next-app myProjectFolder --ts --use-pnpm` 
**React**: (create-react-app)
'npx create-react-app myProjectFolder'

### **Can be in blueprint**
`pnpm create ton@latest myProjectFolder --func --empty` [reference](https://github.com/facebook/create-react-app)
Where:
**_myProjectFolder_** - stands for Project name
**_--func_** - stands for Func contract
**_--empty_** - stands for An empty contract

**Comment by krigga** [comment]
This has been implemented, see readme of https://github.com/ton-org/create-ton
