### ISSUE TITLE
Relative Tact's import don't work 

### ISSUE THREAD

**Issue by defi-pickle** [ton-org/blueprint#59]
relative imports don't work. `Error: Could not resolve import ../imports/messages.tact`
When i have given structure:
```
root/
--imports/
----messages.tact
--jetton/
----jetton_master.tact
```

and with this compile configs:

```
export const compile: CompilerConfig = {
    lang: 'tact',
    target: 'root/jetton/jetton_master.tact',
    options: {
        debug: false,
    },
};
```
linked issue: https://github.com/ton-org/blueprint/issues/51

**Comment by howardpen9** [comment]
+push

Need this feature.

**Comment by anton-trunov** [comment]
This issue should be already resolved, since we fixed it in https://github.com/tact-lang/tact/issues/73

**Comment by defi-pickle** [comment]
Yes i can confirm that it working now!!! 🚀

**Comment by anton-trunov** [comment]
@defi-pickle Thanks a lot for checking! Really appreciate it
