### ISSUE TITLE
TON-Connect-SDK bridge requests don't work

### ISSUE THREAD

**Issue by Cosmodude** [ton-org/blueprint#62]
I am running `npx blueprint run` command in vs code terminal (bash)
Choose the script, testnet, pick TON Connect compatible mobile wallet (Tonkeeper), get this:

Connected to wallet at address: EQAXUIBw-EDVtnCxd65Z2M21KTDr07RoBL6BYf-TBCd6dYvk

Sending transaction. Approve in your wallet...[TON_CONNECT_SDK] Send http-bridge request: {
  method: 'sendTransaction',
  params: [
    '{"messages":[{"address":"EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c","amount":"20000000","payload":"te6cckEBAwEARgABMQAAAAEAAAGJ1Dnp6QAAAAAAAAAAQDRzvAgBAUOAAuoQDh8IGrbOFi71yzsZtqUmHXp2jQCX0Cw/8mCE706wAgAGMTIzk9o5cw=="}],"valid_until":1691483012556,"from":"0:17508070f840d5b670b177ae59d8cdb52930ebd3b46804be8161ff9304277a75","network":"-3"}'
  ],
  id: '70'
}

But nothing happens.
I've checked it connects to the right wallet.

**Comment by howardpen9** [comment]
same

**Comment by Cosmodude** [comment]
found the solution: need to remove the `temp` folder from your blueprint setting.

After it you can reconnect the wallet!

**Comment by Cosmodude** [comment]
Found the solution: need to remove the temp folder from your blueprint setting.

After that, you can reconnect the wallet!
