### ISSUE TITLE
Using mnemonic to connect your wallets

### ISSUE THREAD

**Issue by mhbdev** [ton-org/blueprint#68]
I was trying to deploy my smart contract using mnemonic but I was not able to find any reference or README on what should I set the values of WALLET_MNEMONIC and WALLET_VERSION variables in system env, So as I was using v4 wallet I am creating this issue to share what to put inside WALLET_VERSION's value.

make sure you set "v4" and your seed words should be separated with spaces inside WALLET_MNEMONIC.

Hope this can be helpful to some people.

Something like this:
![image](https://github.com/ton-org/blueprint/assets/53684884/e4064582-c91e-4598-a18f-d32f2b135fc0)

**Comment by ilyar** [comment]
create file `.env`
```ini
WALLET_MNEMONIC="wallet mnemonic words..."
WALLET_VERSION="v5r1" # "v1r1" | "v1r2" | "v1r3" | "v2r1" | "v2r2" | "v3r1" | "v3r2" | "v4" | "v5r1"
```
