### ISSUE TITLE
update verify to read correct verifier registry address + backend urls

### ISSUE THREAD

**Issue by shaharyakir** [ton-org/blueprint#93]
1. backends - should be taken from https://github.com/ton-community/contract-verifier-config/blob/main/config.json
2. verifier registry address - is not canonical and should be taken from the (canonical) sources registry (EQD-BJSVUJviud_Qv7Ymfd3qzXdrmV525e3YDzWQoHIAiInL)

Having said that - opened a PR to update verifier reg address since it was updated -- https://github.com/ton-org/blueprint/pull/92

**Comment by krigga** [comment]
Closing as per the PR
